apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multiply-params
  annotations:
    description: |
      A simple task that multiplies the two provided integers
spec:
  params:
  - name: a
    type: string
    default: "2"
    description: The first integer
  - name: b
    type: string
    default: "2"
    description: The second integer
  steps:
  - name: product
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      echo -n $(( "$(inputs.params.a)" * "$(inputs.params.b)" ))
