apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: add-sum
spec:
  params:
  - name: pl-param-x
    value: "100"
  - name: pl-param-y
    value: "500"
  pipelineRef:
    name: add-sum
